services:
    thinframe.logger:
        class: 'Monolog\Logger'
        factory_service: 'thinframe.logger.factory'
        factory_method: 'createLogger'
    thinframe.logger.factory:
        class: 'ThinFrame\Monolog\LoggerFactory'

    thinframe.logger.handlers.null:
        class: 'Monolog\Handler\NullHandler'

thinframe.logger:
    handlers:
      - 'thinframe.logger.handlers.null'
